const express = require("express");
const router = express.Router();
const fetch = require("../controllers/fetchController");
const {authMiddleware} = require("../middleware/authMiddleware");

// Route to get roles
router.get("/roles", fetch.getRoles);
router.get("/test-sections", (req, res) => {
  console.log('Test sections route hit');
  res.json({ message: 'Sections route is working', query: req.query });
});
router.get("/profile", fetch.getSession);
router.get("/users", fetch.getUsers);
router.get("/locations", fetch.fetchLocations);
router.get("/locations/:location_id", fetch.fetchLocationsById);
router.get("/sections", fetch.getSectionsByLocation);
router.get("/sections/:section_id", fetch.fetchSectionsById);
router.get("/:location_id/sections", fetch.fetchSubLocations);
router.get("/teams/:team_id", fetch.fetchTeamsById);
router.get("/items", authMiddleware, fetch.fetchItems);
router.get("/forms/total-values", authMiddleware, fetch.getTotalFormValues);
router.get("/forms/:location_id", fetch.locationForms);
router.get("/forms", authMiddleware, fetch.fetchForm);
router.get("/branches", authMiddleware, fetch.fetchBrh);
router.get("/warehouses", authMiddleware, fetch.fetchWhs);
router.get("/locations-by-warehouse", authMiddleware, fetch.fetchLocationsByWarehouse);
router.get("/assigned-items/:location_id", fetch.AssignedItems);
router.get("/assigned-items/:location_id/total-amount", authMiddleware, fetch.getAssignedItemsTotalAmount);
router.get("/overall-weight-amount", authMiddleware, fetch.getOverallWeightAndAmount);
router.get("/inventory-analysis", authMiddleware, fetch.getInventoryAnalysis);
router.get("/inventory-details/:form", authMiddleware, fetch.getInventoryDetails);
router.get("/inventory-details-type-quality/:form", authMiddleware, fetch.getInventoryDetailsByTypeQuality);
router.get("/available-warehouses", authMiddleware, fetch.getAvailableWarehouses);
router.get("/test-inventory-data", authMiddleware, fetch.testInventoryData);
router.get("/grade", authMiddleware, fetch.gradeForms);
router.get("/size", authMiddleware, fetch.sizeForms);
router.get("/finish", authMiddleware, fetch.finishForms);
router.get("/extfinish", authMiddleware, fetch.extfinishForms);
router.get("/width", authMiddleware, fetch.widthForms);
router.get("/length", authMiddleware, fetch.lengthForms);
router.get("/mill", authMiddleware, fetch.millForms);
router.get("/heat", authMiddleware, fetch.heatForms);
router.get("/mill-by-heat", authMiddleware, fetch.getMillByHeatAndWarehouse);
router.get("/remarks", authMiddleware, fetch.remarksForms);
router.get("/check-dimension-segment", authMiddleware, fetch.checkDimensionSegment);
router.get("/teams", fetch.fetchTeams);
router.get("/:location_id/assigned-locations", fetch.AssignedTeam);
router.get("/counter", fetch.counterAssigned);
router.get("/checker", fetch.checkerAssigned);
router.get("/checker-sky", fetch.checkerSkyAssigned);
router.get("/teams/:team_id/tag-range", fetch.tagRange);
router.get("/transactions", fetch.GetTransactionsByTeam);
router.get('/transactions/:id', fetch.getTransactionWithBundles);
router.get('/assigned-locations', fetch.getAssignedLocations);
router.get('/location-summary', fetch.getLocationSummary);
router.get('/section', fetch.getSectionByLocation);
router.get('/review-transactions', fetch.getTransactionsByLocationAndSection);
router.get('/teams-with-members', fetch.getTeamWithMembers);
router.get('/checker/get-transactions', fetch.TransactionForChecker);
router.get('/checker/bundles', fetch.BundlesForChecker);
router.get('/locations/:location_id/sections', fetch.sectionCount);
router.get('/locations/:location_id/item-groups', fetch.itemCount);
router.get('/checker/submit-updates', fetch.checkerUpdates);
router.get('/checker/TransactionForChecker', fetch.TransactionForCheck);
router.get('/locations/:location_id/reconciliation', authMiddleware, fetch.getInventoryReconciliation);
router.get('/checker-sku/items', fetch.getCheckerSKUItems);
router.get('/check-existing-checker', fetch.checkExistingChecker);
router.get('/checker-activity-logs', authMiddleware, fetch.getCheckerActivityLogs);
router.get('/debug/users', fetch.debugUsers);

module.exports = router;