const express = require("express");
const router = express.Router();
const post = require("../controllers/postController");
const {authMiddleware} = require("../middleware/authMiddleware");

// Route to register user
// router.post("/signup", post.signup);
// router.post("/login", post.login);
// router.post("/logout", post.logout);
router.post("/users", post.createUser);
router.post("/assign-role", post.assignRole);
router.delete("/users/:user_id", post.deleteUser);
router.post("/locations", post.addLocation);
router.post("/sections", post.addSubLocation);
router.delete("/sections/:section_id", post.deleteSubLocation);
router.delete("/sub-locations/:sub_location_id", post.deleteSubLocation);
router.delete("/locations/:location_id", post.deleteLocation);
router.post("/assign-team", post.assignUserToSubLocation);
router.delete("/assign-team/:location_id/:section_id", post.unassignTeamFromSection);
router.post("/assign-forms", post.assignForms);
router.post("/assigned-items/:location_id", post.deleteItem);
router.delete("/assigned-items/:location_id/:item_id", post.deleteAssignedItem);
router.delete("/assigned-items/:location_id", post.deleteAssignedLocation);
router.post("/teams", post.postTeams);
router.put("/teams/:team_id", post.updateTeam);
router.delete("/teams/:team_id", post.deleteTeam);
router.post("/transactions", post.PostTransactions);
router.post("/checker-transaction", post.PostTransactions);
router.patch('/teams/:team_id/tag-range', post.updateTeamTagPointer);
router.post('/assigned-locations/:location_id/:section_id', post.updateLocationStatus);
router.post('/sections/:location_id/:sectionId/enable-checker', post.enableChecker);
router.post('/users/:user_id', post.updateUser);
router.post('/checker/update-transaction', post.updateTransactions);
router.put('/transactions/:transaction_id', post.updateTransactionById);
router.post('/adjustment-data', authMiddleware, post.getAdjustmentData);
router.post('/counter/update-transaction', post.updateCounterTransaction);
router.post('/checker/verify-transaction', post.verifyTransactions);
router.post('/checker/unverify-transaction', post.unverifyTransactions);
router.post('/checker/add-line-item', post.addLineItem);
router.post('/sections/:location_id/enable-checker-sku', post.enableCheckerSKU);
router.get('/recheck-items/:location_id', post.getRecheckItems);
router.post('/recheck-items/:location_id', post.enableRecheckItems);
router.put('/recheck-items/:location_id', post.updateRecheckItem);
router.delete('/recheck-items/:location_id', post.removeRecheckItems);
router.post('/checker-sku/verify', post.verifyCheckerSKU);
router.post('/assigned-locations/checker/:location_id/:section_id', post.updateCheckerStatus);
router.post('/assign-checker', post.assignCheckerToSection);
module.exports = router;